collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.806383
  brandStrength: 1
  lightness: 0.193617
  brandColors:
    - '#1E1E1E'
    - '#545454'
    - '#FF2501'
    - '#F9F9F9'
    - '#8F8F8F'
  rhythmicContrast: 0.5148936
typography_spectrum: 0.7829787
layout_spectrum: 0.2297872
name: SOCIENT
